"""Preserve rescheduled recurring occurrences"""

from alembic import op
import sqlalchemy as sa

revision = "43c829834e8a"
down_revision = "9a925398dcbf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("occurrences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_start", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("occurrences", schema=None) as batch_op:
        batch_op.drop_column("source_start")

    # ### end Alembic commands ###
