"""Initial academic attendance schema"""

from alembic import op
import sqlalchemy as sa

revision = "9a925398dcbf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_login_attempts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_login_attempts_key"), ["key"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_user_id"), ["user_id"], unique=False)

    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("csrf", sa.String(length=64), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auth_sessions_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "instructors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name"),
    )
    with op.batch_alter_table("instructors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_instructors_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=180), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "key"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.String(length=100), nullable=False),
        sa.Column("institution", sa.String(length=200), nullable=False),
        sa.Column("section", sa.String(length=40), nullable=False),
        sa.Column("timezone", sa.String(length=60), nullable=False),
        sa.Column("target", sa.Double(), nullable=False),
        sa.Column("safety_buffer", sa.Double(), nullable=False),
        sa.Column("risk_sensitivity", sa.String(length=10), nullable=False),
        sa.Column("theme", sa.String(length=10), nullable=False),
        sa.Column("notify_risk", sa.Boolean(), nullable=False),
        sa.Column("notify_upcoming", sa.Boolean(), nullable=False),
        sa.Column("notify_imports", sa.Boolean(), nullable=False),
        sa.CheckConstraint("safety_buffer >= 0 AND safety_buffer <= 25"),
        sa.CheckConstraint("target > 0 AND target <= 100"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "semesters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.CheckConstraint("end_date >= start_date"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name"),
    )
    with op.batch_alter_table("semesters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_semesters_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "calendar_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("semester_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.CheckConstraint("kind IN ('holiday','event','exam')"),
        sa.CheckConstraint("end_date >= start_date"),
        sa.ForeignKeyConstraint(["semester_id"], ["semesters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calendar_events_semester_id"), ["semester_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_calendar_events_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("semester_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("preview", sa.JSON(), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["semester_id"], ["semesters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_documents_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_documents_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "subjects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("semester_id", sa.Integer(), nullable=False),
        sa.Column("instructor_id", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.CheckConstraint("kind IN ('theory', 'practical')"),
        sa.ForeignKeyConstraint(
            ["instructor_id"], ["instructors.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["semester_id"], ["semesters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semester_id", "code"),
    )
    with op.batch_alter_table("subjects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subjects_semester_id"), ["semester_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_subjects_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "baselines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("through_date", sa.Date(), nullable=False),
        sa.Column("attended", sa.Integer(), nullable=False),
        sa.Column("conducted", sa.Integer(), nullable=False),
        sa.CheckConstraint("attended >= 0 AND conducted >= attended"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id"),
    )
    with op.batch_alter_table("baselines", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_baselines_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "reconciliations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("through_date", sa.Date(), nullable=False),
        sa.Column("attended", sa.Integer(), nullable=False),
        sa.Column("conducted", sa.Integer(), nullable=False),
        sa.Column("resolution", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.CheckConstraint("attended >= 0 AND conducted >= attended"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reconciliations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reconciliations_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "timetable",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("room", sa.String(length=100), nullable=False),
        sa.CheckConstraint("end_time > start_time"),
        sa.CheckConstraint("weekday >= 0 AND weekday <= 6"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "weekday", "start_time"),
    )
    with op.batch_alter_table("timetable", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_timetable_subject_id"), ["subject_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_timetable_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "occurrences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("timetable_id", sa.Integer(), nullable=True),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=False),
        sa.Column("room", sa.String(length=100), nullable=False),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("cancellation_reason", sa.String(length=20), nullable=False),
        sa.CheckConstraint("ends_at > starts_at"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["timetable_id"], ["timetable.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "starts_at"),
    )
    with op.batch_alter_table("occurrences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_occurrences_subject_id"), ["subject_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_occurrences_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_occurrences_user_start", ["user_id", "starts_at"], unique=False
        )

    op.create_table(
        "attendance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("occurrence_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("status IN ('present','absent','excused','pending')"),
        sa.ForeignKeyConstraint(
            ["occurrence_id"], ["occurrences.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("occurrence_id"),
    )
    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendance_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_user_id"))

    op.drop_table("attendance")
    with op.batch_alter_table("occurrences", schema=None) as batch_op:
        batch_op.drop_index("ix_occurrences_user_start")
        batch_op.drop_index(batch_op.f("ix_occurrences_user_id"))
        batch_op.drop_index(batch_op.f("ix_occurrences_subject_id"))

    op.drop_table("occurrences")
    with op.batch_alter_table("timetable", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_timetable_user_id"))
        batch_op.drop_index(batch_op.f("ix_timetable_subject_id"))

    op.drop_table("timetable")
    with op.batch_alter_table("reconciliations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reconciliations_user_id"))

    op.drop_table("reconciliations")
    with op.batch_alter_table("baselines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_baselines_user_id"))

    op.drop_table("baselines")
    with op.batch_alter_table("subjects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subjects_user_id"))
        batch_op.drop_index(batch_op.f("ix_subjects_semester_id"))

    op.drop_table("subjects")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_user_id"))
        batch_op.drop_index(batch_op.f("ix_documents_status"))

    op.drop_table("documents")
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calendar_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_calendar_events_semester_id"))

    op.drop_table("calendar_events")
    with op.batch_alter_table("semesters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_semesters_user_id"))

    op.drop_table("semesters")
    op.drop_table("profiles")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))

    op.drop_table("notifications")
    with op.batch_alter_table("instructors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instructors_user_id"))

    op.drop_table("instructors")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_user_id"))

    op.drop_table("auth_sessions")
    with op.batch_alter_table("audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_user_id"))

    op.drop_table("audit")
    op.drop_table("users")
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_attempts_key"))
        batch_op.drop_index(batch_op.f("ix_login_attempts_created_at"))

    op.drop_table("login_attempts")
    # ### end Alembic commands ###
